#!/bin/bash

echo 'deb http://apt.postgresql.org/pub/repos/apt/ xenial-pgdg main' > /etc/apt/sources.list.d/pgdg.list
wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | \
  apt-key add -
apt-get update -y
apt-get install -y postgresql-10

sudo -u postgres bash -c 'createuser -d ${YTD_DATABASE_USER}'
sudo -u postgres bash -c "echo \"alter user ytd with password '${YTD_DATABASE_PASSWORD}';\" | psql"
