#!/bin/bash
add-apt-repository ppa:certbot/certbot
apt-get update
apt-get install certbot

cat <<EOF > /etc/letsencrypt/letsencrypt.conf
rsa-key-size = 4096
email = kerryjbuckley@gmail.com
domains = ytd.kerryb.org
text = True
authenticator = webroot
standalone-supported-challenges = tls-sni-01
webroot-path = /etc/letsencrypt/webroot
EOF

mkdir -p /etc/letsencrypt/webroot/.well-known

letsencrypt-auto certonly --config /etc/letsencrypt/letsencrypt.conf
