Vagrant.configure("2") do |config|
  config.vm.box = "generic/centos7"

  config.vm.network "forwarded_port", guest: 80, host: 8080
  config.vm.network "forwarded_port", guest: 443, host: 4443
  config.vm.synced_folder ".", "/vagrant"

  config.vm.provider "virtualbox" do |v|
    v.memory = 2048
    v.cpus = 2
    v.name = "ytd"
  end

  config.vm.provision "shell", inline: <<~EOF
    cd /vagrant
    sudo ./setup-server.sh
  EOF
end
